import { WORLD_ENVIRONMENT } from "../sim/Environment";
/** Distances use world metres, speeds m/s, accelerations m/s^2, times seconds, angles radians. */
export type MovementConfig = {
	radius: number;
	standingHalfHeight: number;
	crouchingHalfHeight: number;
	standingEyeHeight: number;
	crouchingEyeHeight: number;
	slideEyeHeight: number;
	walkSpeed: number;
	sprintSpeed: number;
	crouchSpeed: number;
	groundAcceleration: number;
	groundDeceleration: number;
	airAcceleration: number;
	airControl: number;
	airDrag: number;
	groundFriction: number;
	groundSteering: number;
	sprintAcceleration: number;
	sprintDeceleration: number;
	reverseBrakingMultiplier: number;
	jumpVelocity: number;
	gravity: number;
	coyoteTime: number;
	jumpBufferTime: number;
	/** After a jump, ignore ground contact so the body can leave the surface. */
	jumpGroundGraceTime: number;
	/** Keep reporting grounded briefly after contact loss (stairs/lips). */
	groundStickTime: number;
	sprintForwardThreshold: number;
	omnidirectionalSprint: boolean;
	slideMinStartSpeed: number;
	slideEntryBoost: number;
	slideFriction: number;
	slideDrag: number;
	slideSteering: number;
	slideExitSpeed: number;
	airSlideBufferTime: number;
	airSlideMinHorizontalSpeed: number;
	landingMomentumRetention: number;
	groundProbeDistance: number;
	maxWalkableSlope: number;
	/** Above this ground angle, surfaces turn slippery (slide off, no perch). */
	slopeSlideAngle: number;
	slopeSlideFactor: number;
	stepHeight: number;
	stepMinWidth: number;
	collisionSkinWidth: number;
	physicalHorizontalSpeedCap: number;
	wallProbeDistance: number;
	wallMaxNormalY: number;
	wallContactGraceTime: number;
	wallJumpAwaySpeed: number;
	wallJumpUpSpeed: number;
	wallJumpTravelSpeed: number;
	wallJumpIntentWeight: number;
	wallJumpLookLift: number;
	sameWallCooldown: number;
	sameWallNormalDot: number;
	sameWallSeparation: number;
	maxFallSpeed: number;
};

export const DEFAULT_MOVEMENT_CONFIG: MovementConfig = {
	radius: 0.35,
	standingHalfHeight: 0.55,
	crouchingHalfHeight: 0.22,
	standingEyeHeight: 1.48,
	crouchingEyeHeight: 1.02,
	slideEyeHeight: 0.9,
	walkSpeed: 6.2,
	sprintSpeed: 9.1,
	crouchSpeed: 3.4,
	groundAcceleration: 34,
	groundDeceleration: 25,
	airAcceleration: 12,
	airControl: 0.42,
	airDrag: 0.04,
	groundFriction: 9,
	groundSteering: 9,
	sprintAcceleration: 27,
	sprintDeceleration: 18,
	reverseBrakingMultiplier: 2.4,
	jumpVelocity: 9.2,
	gravity: -WORLD_ENVIRONMENT.gravity.y,
	coyoteTime: 0.1,
	jumpBufferTime: 0.12,
	jumpGroundGraceTime: 0.12,
	groundStickTime: 0.06,
	sprintForwardThreshold: 0.55,
	omnidirectionalSprint: false,
	slideMinStartSpeed: 5.5,
	slideEntryBoost: 1.1,
	slideFriction: 7.5,
	slideDrag: 0.45,
	slideSteering: 2.35,
	slideExitSpeed: 3.2,
	airSlideBufferTime: 0.35,
	airSlideMinHorizontalSpeed: 5.5,
	landingMomentumRetention: 0.98,
	groundProbeDistance: 0.14,
	maxWalkableSlope: 0.85,
	slopeSlideAngle: 0.72,
	slopeSlideFactor: 0.5,
	stepHeight: 0.3,
	stepMinWidth: 0.2,
	collisionSkinWidth: 0.015,
	physicalHorizontalSpeedCap: 35,
	wallProbeDistance: 0.16,
	wallMaxNormalY: 0.25,
	wallContactGraceTime: 0.08,
	wallJumpAwaySpeed: 2.4,
	wallJumpUpSpeed: 9.4,
	wallJumpTravelSpeed: 8.5,
	wallJumpIntentWeight: 0.8,
	wallJumpLookLift: 2,
	sameWallCooldown: 0.35,
	sameWallNormalDot: 0.92,
	sameWallSeparation: 0.7,
	maxFallSpeed: 40,
};
